version: '2.0'
services:
  jenkins:
    container_name: ledgeriumjenkins
    image: ledgeriumjenkins:v1
    environment: 
      JAVA_OPTS: "-Djava.awt.headless=true"  
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked  
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - JOBSPATH:/var/jenkins_home/jobs  
    networks:
      - test_net
networks:
  test_net:
    external: true
 
